apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah-push
spec:
  params:
  - name: image-name
    type: string
  - name: manifest-name
    type: string
  workspaces:
  - name: container-storage
    description: Persistent volume to store container images
    mountPath: /var/lib/containers
  steps:
  - name: push
    image: quay.io/podman/stable
    script: |
      #!/bin/bash
      set -Eeuo pipefail
      export STORAGE_DRIVER=vfs
      buildah manifest push --all $(params.manifest-name) docker://$(params.image-name)
