apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm-install
spec:
  params:
  - name: context-dir
    type: string
    default: .
  workspaces:
  - name: source-workspace
    description: Workspace containing source code
  steps:
  - name: npm-install
    image: registry.access.redhat.com/ubi9/nodejs-20:latest
    script: |
      #!/bin/bash
      set -Eeuo pipefail
      cd $(workspaces.source-workspace.path)/$(params.context-dir)
      npm install
